### ISSUE TITLE
勘误

### ISSUE THREAD

**Issue by SourceCode1037** [boyu-ai/Hands-on-RL#1]
[马尔可夫决策过程](https://hrl.boyuai.com/chapter/1/%E9%A9%AC%E5%B0%94%E5%8F%AF%E5%A4%AB%E5%86%B3%E7%AD%96%E8%BF%87%E7%A8%8B) 第三行:

马尔可夫决策过程 (Markov ~~Reward~~ Decision Process) 是强化学习的基础。

**Comment by RockySJ** [comment]
> [马尔可夫决策过程](https://hrl.boyuai.com/chapter/1/%E9%A9%AC%E5%B0%94%E5%8F%AF%E5%A4%AB%E5%86%B3%E7%AD%96%E8%BF%87%E7%A8%8B) 第三行:
> 
> 马尔可夫决策过程 (Markov ~Reward~ Decision Process) 是强化学习的基础。

谢谢

**Comment by RockySJ** [comment]
我们会在下次更新中修正这个错误，非常感谢您的反馈！
