### ISSUE TITLE
请教，动态规划算法计算Q(s,a)价值

### ISSUE THREAD

**Issue by goodzhangbobo** [boyu-ai/Hands-on-RL#11]
for循环最内圈，qsa += p * (r + self.gamma * self.v[next_state] *  (1 - done))，
r在for循环最内圈多次加和，根据公式： Q(s, a)=r+ gamma * sum(p * v(s'));
是不是应该放在for循环外只加一次？

**Comment by RockySJ** [comment]
reward不会被多次累加，因为前面有个p，所有的p加和为1。

这么写的原因是我们用的环境的奖励函数与下一个状态有关，即r(s,a,s')，而不再是r(s,a)。考虑到在(s,a)下，可能会进入到不同的s'上，此时的bellman equation应该为q(s,a) = \sum_{s'} p(s'|s,a) (r(s,a,s') + \gamma * v(s'))

**Comment by shao12138** [comment]
我之前也提到过，在closed里面，换成冰湖环境和寻宝环境原代码不适用了。

**Comment by shao12138** [comment]
在“BUG”中

**Comment by RockySJ** [comment]
> 我之前也提到过，在closed里面，换成冰湖环境和寻宝环境原代码不适用了。

你俩的问题不是同一问题。此issue中的问题在于奖励函数与下一个状态有关时的bellman方程，你提的issue中的问题是价值函数是同步更新还是异步更新的问题。此外，我在之前的issue中提供了寻宝环境的代码和实验结果，请移步查看。

**Comment by shao12138** [comment]
感谢

**Comment by goodzhangbobo** [comment]
感谢  明白了。看完你的回复 我再看代码，明白了。

**Comment by ENg-122** [comment]
与下一个状态有关的这种情况，Q(s,a)的算法我在书里似乎没有找到
