### ISSUE TITLE
MADDPG中训练结果并非是欺骗对抗智能体，而是比谁快速到绿色目标点。

### ISSUE THREAD

**Issue by shao12138** [boyu-ai/Hands-on-RL#12]
![微信图片_20220723144346](https://user-images.githubusercontent.com/95729948/180593842-0864c54b-a5f6-4b7e-8bc1-00bd60cd8364.png)

奖励曲线跟官方一致。

**Comment by shao12138** [comment]
**似乎并不是：**可以看到，正常智能体agent_0和agent_1的回报结果完全一致，这是因为它们的奖励函数完全一样。正常智能体最终保持了正向的回报，说明它们通过合作成功地占领了两个不同的地点，进而让对抗智能体无法知道哪个地点是目标地点。另外，我们也可以发现 MADDPG 的收敛速度和稳定性都比较不错。

**Comment by shao12138** [comment]
![捕获](https://user-images.githubusercontent.com/95729948/180595892-1dbcd7be-1277-404b-a3f8-ac9f4f0f5351.PNG)

**Comment by shao12138** [comment]
正常的话敌人的曲线应该下降的，实际中的曲线确实增加的，这明显不符合实际情况。

**Comment by RockySJ** [comment]
环境设置和结果曲线应该没有问题，请参考
1. https://www.pettingzoo.ml/mpe/simple_adversary
2. https://github.com/wsjeon/maddpg-rllib/tree/master/plots

**Comment by shao12138** [comment]
虽然结果符合，但是训练中还是比速度快，而不存在agent迷惑adversary，有点难以理解。

**Comment by KornbergFresnel** [comment]
@shao12138 可以参考环境介绍，应当解释得很清楚：

1. The adversary is rewarded based on distance to the target, but it doesn’t know which landmark is the target landmark.
2. Agent observation space: `[self_pos, self_vel, goal_rel_position, landmark_rel_position, other_agent_rel_positions]` （这里有goal）
3. Adversary observation space: `[landmark_rel_position, other_agents_rel_positions]` （这里没有goal）

**Comment by shao12138** [comment]
感谢，本人能力不是很好，麻烦了。
