### ISSUE TITLE
找不到网站的反馈渠道，在这里反馈一下。

### ISSUE THREAD

**Issue by leshui1991** [boyu-ai/Hands-on-RL#14]
![20220902_121840000_iOS](https://user-images.githubusercontent.com/30827168/188147308-bdef403e-b82c-47e4-af40-c81c09c8e394.png)
两个边侧栏能不能加个隐藏的按钮，在IPAD上的体验很不好。

**Comment by RockySJ** [comment]
抱歉，暂时没有考虑IPAD上的体验优化。为了您更好的阅读体验，请在PC端浏览 :)
