### ISSUE TITLE
a little piece of advice and modification in chapter 3.3.2 价值函数

### ISSUE THREAD

**Issue by erjiaxiao** [boyu-ai/Hands-on-RL#17]
Recently I've been reading the book for learning reinforcement learning. Thanks for such a wonderful tutorial with complete code! And I found that a concept is not clear for a RL beginner in chapter 3.3.2 价值函数. 

here is the link: https://hrl.boyuai.com/chapter/1/%E9%A9%AC%E5%B0%94%E5%8F%AF%E5%A4%AB%E5%86%B3%E7%AD%96%E8%BF%87%E7%A8%8B#331-%E5%9B%9E%E6%8A%A5

The original version is:
在马尔可夫奖励过程中，一个状态的期望回报被称为这个状态的价值（value）。所有状态的价值就组成了价值函数（value function），价值函数的输入为某个状态，输出为这个状态的价值。

a little piece of advice is:
在马尔可夫奖励过程中，一个状态的期望回报（即从这个状态开始的未来期望累计回报）被称为这个状态的价值（value）。所有状态的价值就组成了价值函数（value function），价值函数的输入为某个状态，输出为这个状态的价值。

Hope this helps!

**Comment by RockySJ** [comment]
谢谢，将在下次更新时添加如下解释“（即从这个状态出发的未来累积奖励的期望）”
