### ISSUE TITLE
"每10条序列打印一下这10条序列的平均回报" 是否有误

### ISSUE THREAD

**Issue by ihewro** [boyu-ai/Hands-on-RL#2]
https://hrl.boyuai.com/chapter/1/%E6%97%B6%E5%BA%8F%E5%B7%AE%E5%88%86%E7%AE%97%E6%B3%95#sarsa

在这篇文章的搜索”# 每10条序列打印一下这10条序列的平均回报“，可以找到这个代码注释

这里每个进度条内部是50个序列，所以这里面应该计算每50条序列的平均回报吧

**Comment by RockySJ** [comment]
的确是每10条打印一次。此代码运行过程中，进度条会不断增长，最终增长到50条序列，其中每10条序列会打印一次结果。
