### ISSUE TITLE
勘误: 强化学习基础篇-多臂老虎机-ϵ-贪心算法 DecayingEpsilonGreedy 代码缩进/排版问题

### ISSUE THREAD

**Issue by earlytobed** [boyu-ai/Hands-on-RL#20]
阅读纸书时发现代码块 class DecayingEpsilonGreedy 有缩进/排版错误， return k 应属于 run_one_step 函数，即少了一层缩进。同时发现网页版本中也存在此问题，故在此提 issue ，供参考。

注：
1. 网页版本中 [多臂老虎机#24-ϵ-贪心算法](https://hrl.boyuai.com/chapter/1/%E5%A4%9A%E8%87%82%E8%80%81%E8%99%8E%E6%9C%BA#24-%CF%B5-%E8%B4%AA%E5%BF%83%E7%AE%97%E6%B3%95) 存在此问题；
2. 对应纸书 (2022 年 5 月第 1 版) 的 13 页也有此问题，已在异步社区提交了勘误，尚未有编辑审核；
3. 本仓库中的 jupyter notebook 没问题，可以运行；

**Comment by RockySJ** [comment]
感谢指出！网页版本已修改
