### ISSUE TITLE
DQN扩展代码有问题

### ISSUE THREAD

**Issue by shao12138** [boyu-ai/Hands-on-RL#6]
Double DQN和DQN学习结果一模一样，而且根本无法区分。

**Comment by Winter0506** [comment]
> Double DQN和DQN学习结果一模一样，而且根本无法区分。

` if self.dqn_type == 'DoubleDQN':  #DQN与Double DQN的区别
            max_action = self.q_net(next_states).max(1)[1].view(-1, 1)
            max_next_q_values = self.target_q_net(next_states).gather(1, max_action)
        else:
            # 下个状态的最大Q值
            max_next_q_values = self.target_q_net(next_states).max(1)[0].view(
                -1, 1)
        q_targets = rewards + self.gamma * max_next_q_values * (1 - dones
                                                                )  # TD误差目标`

**Comment by Winter0506** [comment]
> Double DQN和DQN学习结果一模一样，而且根本无法区分。

```
 if self.dqn_type == 'DoubleDQN':  #DQN与Double DQN的区别
            max_action = self.q_net(next_states).max(1)[1].view(-1, 1)
            max_next_q_values = self.target_q_net(next_states).gather(1, max_action)
        else:
            # 下个状态的最大Q值
            max_next_q_values = self.target_q_net(next_states).max(1)[0].view(
                -1, 1)
        q_targets = rewards + self.gamma * max_next_q_values * (1 - dones
                                                                )  # TD误差目标
```

**Comment by Winter0506** [comment]
> Double DQN和DQN学习结果一模一样，而且根本无法区分。
书上代码是这样的：
```
 if self.dqn_type == 'DoubleDQN':  #DQN与Double DQN的区别
            max_action = self.q_net(next_states).max(1)[1].view(-1, 1)
            max_next_q_values = self.target_q_net(next_states).gather(1, max_action)
 else:
            # 下个状态的最大Q值
            max_next_q_values = self.target_q_net(next_states).max(1)[0].view(
                -1, 1)
q_targets = rewards + self.gamma * max_next_q_values * (1 - dones
                                                                )  # TD误差目标
```

**Comment by shao12138** [comment]
书上没错，但是Github上少了判断语句



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月5日(星期四) 中午11:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [boyu-ai/Hands-on-RL] DQN扩展代码有问题 (Issue #6)





  
Double DQN和DQN学习结果一模一样，而且根本无法区分。
 书上代码是这样的：
   if self.dqn_type == 'DoubleDQN':  #DQN与Double DQN的区别             max_action = self.q_net(next_states).max(1)[1].view(-1, 1)             max_next_q_values = self.target_q_net(next_states).gather(1, max_action)  else:             # 下个状态的最大Q值             max_next_q_values = self.target_q_net(next_states).max(1)[0].view(                 -1, 1) q_targets = rewards + self.gamma * max_next_q_values * (1 - dones                                                                 )  # TD误差目标

**Comment by RockySJ** [comment]
已修复，感谢指出～
