### ISSUE TITLE
用spyder跑PPO代码，kernel自动关闭了

### ISSUE THREAD

**Issue by Shawkncok** [boyu-ai/Hands-on-RL#67]
我用spyder跑PPO的代码，跑了10次interation之后，kernel自动关闭，也没有现实图像

提示现实如下，不知道为什么
希望能帮忙解答

![image](https://github.com/boyu-ai/Hands-on-RL/assets/129776579/fe4acf32-bd53-4a6f-a0dd-a3a21f277424)
![image](https://github.com/boyu-ai/Hands-on-RL/assets/129776579/2386b3f3-61d5-4916-983a-43d03f5cb963)
![image](https://github.com/boyu-ai/Hands-on-RL/assets/129776579/d13a9188-7cba-411b-a08c-83cc5999c612)
![image](https://github.com/boyu-ai/Hands-on-RL/assets/129776579/44c186aa-9c5c-476f-ab3c-4e8260b23841)

**Comment by cnygxdeyxx** [comment]
[https://zhuanlan.zhihu.com/p/371649016](url)
分享这个解决方案，可以翻一下评论区。我是通过删除环境lib中的libiomp5md.dll文件解决的
