### ISSUE TITLE
PPO在单摆实验中为什么要对reward=(reward+8)/8的修改呢？

### ISSUE THREAD

**Issue by xxoospring** [boyu-ai/Hands-on-RL#70]
如题，如果注释掉这行，好像算法就不收敛了

**Comment by xxoospring** [comment]
是不是约等于对reward做了normalize, 约束到[-1, 1]之间呢？我把上述换成 rewards = F.sigmoid(rewards),也是能正常收敛的。如果是这个原因，那又是为什么这个较大范围的rewards会导致训练不收敛呢？

**Comment by cnygxdeyxx** [comment]
可以看一下这篇文章中关于奖励函数设置部分的内容：[https://www.jiqizhixin.com/articles/2017-09-11-7](url)
以及附上文章引用的原视频
YouTube链接：[https://www.youtube.com/watch?v=8EcdaCk9KaQ](url)
bilibili链接：[https://www.bilibili.com/video/BV1Da4y1D7BQ](url)
**总结如下**
### 奖励函数的调整
在强化学习中，奖励值的范围和分布对算法的收敛性和性能有很大的影响。对奖励进行归一化或缩放，能够更容易地训练模型。
### 原因
- **数值稳定性**：通过对奖励进行变换，可以将其范围缩小到一个更容易处理的数值范围，这有助于避免梯度爆炸或梯度消失的问题，从而提高数值稳定性。 
- **训练效率**：归一化奖励可以使得神经网络更快地学习到最优策略，因为奖励的分布更集中，训练过程中的梯度更新更加稳定。 
-  **一致性**：在不同的任务中保持奖励值的范围一致，可以使得算法更具通用性和鲁棒性。
