### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by shao12138** [boyu-ai/Hands-on-RL#8]
动态规划：策略评估中，self.v = new_v 应该缩进到for里面的，否则位置2用到的1的v值函数初始化时候的0，可以笔算验证一下。

**Comment by shao12138** [comment]
修正方法：全部缩进到for里面
new_v[s] = sum(qsa_list)  # 状态价值函数和动作价值函数之间的关系
max_diff = max(max_diff, abs(new_v[s] - self.v[s]))
self.v[s] = sum(qsa_list)

**Comment by RockySJ** [comment]
两种实现方式都是可以的，请参考Sutton的书的4.5 Asynchronous Dynamic Programming一节。

**Comment by RockySJ** [comment]
ref: https://web.stanford.edu/class/psych209/Readings/SuttonBartoIPRLBook2ndEd.pdf

**Comment by shao12138** [comment]
比如，寻宝游戏中，按照你这里代码训练出来的结果没有任何作用。

**Comment by RockySJ** [comment]
@shao12138 麻烦您提供一下环境和代码，谢谢，我们尝试一下

**Comment by shao12138** [comment]
class CliffWalkingEnv:
    def __init__(self, ncol, nrow, end=()):
        self.ncol = ncol  # 定义环境的宽
        self.nrow = nrow  # 定义环境的高
        self.end = end  # 终点
        self.P = self.createP()  # 转移矩阵P[state][action] = [(p, next_state, reward, done)]，包含下一个状态和奖励
 
    def createP(self):
        P = [[[] for j in range(4)] for i in range(self.nrow * self.ncol)]  # 初始化
        #原点(0,0)定义在左上角
        for i in range(self.nrow):
            for j in range(self.ncol):
                for a in range(4):
                    if (j, i) == self.end:  # 位置在或者终点，因为无法继续交互，任何动作奖励都为0
                        P[i * self.ncol + j][a] = [(1, i * self.ncol + j, 0, True)]
                        continue
                    # 其他位置
                    next_x=j
                    next_y=i
                    if a == 0:
                        next_x -= 1  # left
                    elif a == 1:
                        next_x += 1  # right
                    elif a == 2:
                        next_y += 1  # down
                    elif a == 3:
                        next_y -= 1  # up
 
                    if next_x < 0:
                        next_x = 0
                    if next_x >= self.nrow:
                        next_x = self.nrow - 1
                    if next_y < 0:
                        next_y = 0
                    if next_y >= self.ncol:
                        next_y = self.ncol - 1
                    next_state = next_y * self.ncol + next_x
                    reward = -1
                    done = False
                    if (j, i) == self.end:  # End
                        reward = 0
                        done = True
                    P[i * self.ncol + j][a] = [(1, next_state, reward, done)]
        return P

**Comment by shao12138** [comment]
#策略迭代
env = CliffWalkingEnv(ncol=5, nrow=5,  end=(3, 1))  # 横坐标3，纵坐标1
action_meaning = ['<', '>', 'v','^']
theta = 0.00001
gamma = 1
agent = PolicyIteration(env, theta, gamma)
agent.policy_iteration()
print_agent(agent, action_meaning, [], [8])  # 5, 7, 11, 1

**Comment by shao12138** [comment]
import copy
from environment import CliffWalkingEnv
 
class PolicyIteration:
    """ 策略迭代 """
 
    def __init__(self, env, theta, gamma):
        self.env = env
        self.v = [0] * self.env.ncol * self.env.nrow  # 初始化价值为0
        self.pi = [[0.25, 0.25, 0.25, 0.25] for i in range(self.env.ncol * self.env.nrow)]  # 初始化为均匀随机策略
        self.theta = theta  # 策略评估收敛阈值
        self.gamma = gamma  # 折扣因子
 
    def policy_evaluation(self):  # 策略评估
        cnt = 1  # 计数器
        while 1:
            max_diff = 0
            new_v = [0] * self.env.ncol * self.env.nrow
            for s in range(self.env.ncol * self.env.nrow):
                qsa_list = []
                for a in range(4):
                    qsa = 0
                    for res in self.env.P[s][a]:
                        p, next_state, r, done = res
                        qsa += self.pi[s][a] * p * (r + self.gamma * self.v[next_state] * (1 - done)) # 本章节环境比较特殊，奖励和下一个状态有关，所以需要和状态转移概率相乘
                    qsa_list.append(qsa)
                new_v[s] = sum(qsa_list)  # 状态价值函数和动作价值函数之间的关系
                max_diff = max(max_diff, abs(new_v[s] - self.v[s]))
                self.v[s] = sum(qsa_list)
            # print("状态价值：", cnt)
            # for i in range(self.env.nrow):
            #     for j in range(self.env.ncol):
            #         print('%6.6s' % ('%.3f' % self.v[i * self.env.ncol + j]), end=' ')  # 为了输出美观，保持输出6个字符
            #     print()
            if max_diff < self.theta: break
            cnt += 1
        print("策略评估进行%d轮后完成" % cnt)
 
    def policy_improvement(self):  # 策略提升
        for s in range(self.env.nrow * self.env.ncol):
            qsa_list = []
            for a in range(4):
                qsa = 0
                for res in self.env.P[s][a]:
                    p, next_state, r, done = res
                    qsa += p * (r + self.gamma * self.v[next_state] * (1 - done))
                qsa_list.append(qsa)
            maxq = max(qsa_list)
            cntq = qsa_list.count(maxq)
            self.pi[s] = [1 / cntq if q == maxq else 0 for q in qsa_list]  # 让相同的动作价值均分概率
        print("策略提升完成")
        return self.pi
 
    def policy_iteration(self):  # 策略迭代
        while 1:
            self.policy_evaluation()
            old_pi = copy.deepcopy(self.pi)  # 将列表进行深拷贝，方便接下来进行比较
            new_pi = self.policy_improvement()
            if old_pi == new_pi: break
 
def print_agent(agent, action_meaning, disaster=[], end=[]):
    print("状态价值：")
    for i in range(agent.env.nrow):
        for j in range(agent.env.ncol):
            print('%6.6s' % ('%.3f' % agent.v[i * agent.env.ncol + j]), end=' ')  # 为了输出美观，保持输出6个字符
        print()
    print("策略：")
    for i in range(agent.env.nrow):
        for j in range(agent.env.ncol):
            if (i * agent.env.ncol + j) in disaster:  # 一些特殊的状态，例如Cliff Walking中的悬崖
                print('****', end=' ')
            elif (i * agent.env.ncol + j) in end:  # 终点
                print('EEEE', end=' ')
            else:
                a = agent.pi[i * agent.env.ncol + j]
                pi_str = ''
                for k in range(len(action_meaning)):
                    pi_str += action_meaning[k] if a[k] > 0 else 'o'
                print(pi_str, end=' ')
        print()
 
env = CliffWalkingEnv(ncol=5, nrow=5,  end=(3, 1))  # 横坐标3，纵坐标1
action_meaning = ['<', '>', 'v','^']
theta = 0.00001
gamma = 1
agent = PolicyIteration(env, theta, gamma)
agent.policy_iteration()
print_agent(agent, action_meaning, [], [8])  # 5, 7, 11, 12
===========================================================
策略评估进行338轮后完成
策略提升完成
策略评估进行5轮后完成
策略提升完成
策略评估进行1轮后完成
策略提升完成
状态价值：
-4.000 -3.000 -2.000 -1.000 -2.000 
-3.000 -2.000 -1.000  0.000 -1.000 
-4.000 -3.000 -2.000 -1.000 -2.000 
-5.000 -4.000 -3.000 -2.000 -3.000 
-6.000 -5.000 -4.000 -3.000 -4.000 
策略：
o>vo o>vo o>vo oovo <ovo 
o>oo o>oo o>oo EEEE <ooo 
o>o^ o>o^ o>o^ ooo^ <oo^ 
o>o^ o>o^ o>o^ ooo^ <oo^ 
o>o^ o>o^ o>o^ ooo^ <oo^

**Comment by RockySJ** [comment]
class MazeEnv:
    """ 悬崖漫步环境"""
    def __init__(self, ncol=5, nrow=5):
        self.ncol = ncol  # 定义网格世界的列
        self.nrow = nrow  # 定义网格世界的行
        # 转移矩阵P[state][action] = [(p, next_state, reward, done)]包含下一个状态和奖励
        self.P = self.createP()

    def createP(self):
        # 初始化
        P = [[[] for j in range(4)] for i in range(self.nrow * self.ncol)]
        # 4种动作, change[0]:上,change[1]:下, change[2]:左, change[3]:右。坐标系原点(0,0)定义在左上角
        change = [[0, -1], [0, 1], [-1, 0], [1, 0]]
        for i in range(self.nrow):
            for j in range(self.ncol):
                for a in range(4):
                    # 位置在目标状态,因为无法继续交互,任何动作奖励都为0
                    if i == self.nrow - 1 and j == 2:
                        P[i * self.ncol + j][a] = [(1, i * self.ncol + j, 0, True)]
                        continue
                    # 其他位置
                    next_x = min(self.ncol - 1, max(0, j + change[a][0]))
                    next_y = min(self.nrow - 1, max(0, i + change[a][1]))
                    next_state = next_y * self.ncol + next_x
                    reward = -1
                    done = False
                    # 下一个位置在终点
                    if next_y == self.nrow - 1 and next_x == 2:
                        done = True
                        reward = 0
                    P[i * self.ncol + j][a] = [(1, next_state, reward, done)]
        return P

**Comment by RockySJ** [comment]
``` python

class MazeEnv:
    """ 寻宝环境"""
    def __init__(self, ncol=5, nrow=5):
        self.ncol = ncol  # 定义网格世界的列
        self.nrow = nrow  # 定义网格世界的行
        # 转移矩阵P[state][action] = [(p, next_state, reward, done)]包含下一个状态和奖励
        self.P = self.createP()

    def createP(self):
        # 初始化
        P = [[[] for j in range(4)] for i in range(self.nrow * self.ncol)]
        # 4种动作, change[0]:上,change[1]:下, change[2]:左, change[3]:右。坐标系原点(0,0)定义在左上角
        change = [[0, -1], [0, 1], [-1, 0], [1, 0]]
        for i in range(self.nrow):
            for j in range(self.ncol):
                for a in range(4):
                    # 位置在目标状态,因为无法继续交互,任何动作奖励都为0
                    if i == self.nrow - 1 and j == 2:
                        P[i * self.ncol + j][a] = [(1, i * self.ncol + j, 0, True)]
                        continue
                    # 其他位置
                    next_x = min(self.ncol - 1, max(0, j + change[a][0]))
                    next_y = min(self.nrow - 1, max(0, i + change[a][1]))
                    next_state = next_y * self.ncol + next_x
                    reward = -1
                    done = False
                    # 下一个位置在终点
                    if next_y == self.nrow - 1 and next_x == 2:
                        done = True
                        reward = 0
                    P[i * self.ncol + j][a] = [(1, next_state, reward, done)]
        return P

```

**Comment by RockySJ** [comment]
``` python
def print_agent(agent, action_meaning, end=[]):
    print("状态价值：")
    for i in range(agent.env.nrow):
        for j in range(agent.env.ncol):
            # 为了输出美观,保持输出6个字符
            print('%6.6s' % ('%.3f' % agent.v[i * agent.env.ncol + j]),
                  end=' ')
        print()

    print("策略：")
    for i in range(agent.env.nrow):
        for j in range(agent.env.ncol):
            # 一些特殊的状态,例如悬崖漫步中的悬崖
            if (i * agent.env.ncol + j) in end:  # 目标状态
                print('EEEE', end=' ')
            else:
                a = agent.pi[i * agent.env.ncol + j]
                pi_str = ''
                for k in range(len(action_meaning)):
                    pi_str += action_meaning[k] if a[k] > 0 else 'o'
                print(pi_str, end=' ')
        print()


env = MazeEnv()
action_meaning = ['^', 'v', '<', '>']
theta = 0.001
gamma = 0.9
agent = PolicyIteration(env, theta, gamma)
agent.policy_iteration()
print_agent(agent, action_meaning, [22])
```

**Comment by RockySJ** [comment]
策略迭代的实验结果为

策略评估进行59轮后完成
策略提升完成
策略评估进行7轮后完成
策略提升完成
策略评估进行1轮后完成
策略提升完成
状态价值：
-4.095 -3.439 -2.710 -3.439 -4.095 
-3.439 -2.710 -1.900 -2.710 -3.439 
-2.710 -1.900 -1.000 -1.900 -2.710 
-1.900 -1.000  0.000 -1.000 -1.900 
-1.000  0.000  0.000  0.000 -1.000 
策略：
ovo> ovo> ovoo ov<o ov<o 
ovo> ovo> ovoo ov<o ov<o 
ovo> ovo> ovoo ov<o ov<o 
ovo> ovo> ovoo ov<o ov<o 
ooo> ooo> EEEE oo<o oo<o
